' Colors

!global $NK_COMPONENT_BORDER_COLOR = "#A9783D"
!global $NK_COMPONENT_COLOR = "#BE8A4A"
!global $NK_CONTAINER_BORDER_COLOR = "#3C907B"
!global $NK_CONTAINER_COLOR = "#4F9E81"
!global $NK_ENTERPRISE_BORDER_COLOR = "#555555"
!global $NK_ENTERPRISE_COLOR = "#FFFFFF"
!global $NK_SYSTEM_BORDER_COLOR = "#42688A"
!global $NK_SYSTEM_COLOR = "#4F7CA4"

!global $NK_FG_COLOR = "#FFFFFF"

UpdateElementStyle(person, $bgColor=$NK_SYSTEM_COLOR, $fontColor=$NK_FG_COLOR, $borderColor=$NK_SYSTEM_BORDER_COLOR)
UpdateElementStyle(system, $bgColor=$NK_SYSTEM_COLOR, $fontColor=$NK_FG_COLOR, $borderColor=$NK_SYSTEM_BORDER_COLOR)
UpdateElementStyle(container, $bgColor=$NK_CONTAINER_COLOR, $fontColor=$NK_FG_COLOR, $borderColor=$NK_CONTAINER_BORDER_COLOR)
UpdateElementStyle(component, $bgColor=$NK_COMPONENT_COLOR, $fontColor=$NK_FG_COLOR, $borderColor=$NK_COMPONENT_BORDER_COLOR)
