!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include C4.puml

!procedure LAYOUT_WITH_LEGEND()
hide stereotype
legend right
|<color:$LEGEND_TITLE_COLOR>**Legend**</color> |
|<$NK_SYSTEM_COLOR> system / person |
|<$EXTERNAL_SYSTEM_BG_COLOR> existing system / person |
endlegend
!endprocedure
