!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!global $NK_DIAGRAM_TYPE = "context"
!include https://raw.githubusercontent.com/hindsholm/C4-PlantUML/stdlib-wrapper/C4_Nykredit.puml
