@startuml "Kursinformation - Component Diagram"
'!include https://raw.githubusercontent.com/Nykredit/C4-PlantUML/production/C4_Container.puml
!include C4_Component.puml

LAYOUT_WITH_LEGEND()

Person(actorA, "Primary user", "Description")
Person_Ext(actorB, "Secondary user", "Description")

Container(contFrontend, "Frontend", "Tech", "Description")

Container_Boundary(contBoundary, "Backend") {
  Component(compA, "Component A", "A tech", "Description")
  Component(compB, "Component B", "B tech", "Description")
  Component(compC, "Component C", "C tech", "Description")
  ComponentDb(compDb, "Component DB", "Db Tech", "Description")
  Rel(compA, compB, "Some stuff")
  Rel(compA, compC, "Some other stuff")
}

Boundary(custBoundary, "Some boundary", "Custom") {
  System_Ext(systemB, "Existing system", "Description")
  ContainerDb(contDb, "DB for sys", "Description")
}

Rel(contFrontend, compA, "calls")
Rel(compB, contDb, "Persists")
Rel(compC, systemB, "Use a backend")

@enduml