@startuml "Kursinformation - Container Diagram"
'!include https://raw.githubusercontent.com/Nykredit/C4-PlantUML/production/C4_Container.puml
!include C4_Container.puml

LAYOUT_WITH_LEGEND()

Person_Ext(actorB, "Secondary user", "Description")

Enterprise_Boundary(entBoundary, "Nykredit") {
  Person(actorA, "Primary user", "Description")
  System_Boundary(sysBoundary, "System in focus") {
    Container(contFrontend, "Frontend", "Tech", "Description")

    Container(contBackend, "Backend", "Tech", "Description")
    ContainerDb(contDb, "DB for sys", "Oracle", "Description")
    Rel(contFrontend, contBackend, "Calls", "REST")
    Rel(contBackend, contDb, "Persists")
  }
}

Boundary(custBoundary, "Some boundary", "Custom boundary name") {
  System_Ext(systemB, "Existing system", "Description")
  SystemDb_ext(systemDbExt, "DB for existing system", "Description")
}

Rel(actorA, contFrontend, "Says hello", "REST")
Rel(actorB, contFrontend, "Says hi", "SOAP")
Rel(contBackend, systemB, "Use a backend")
Rel(contBackend, systemDbExt, "Persists")

@enduml